CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    picture VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS code (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL
);
