apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: app-dev
type: Opaque
data:
  SPRING_R2DBC_USERNAME: cG9zdGdyZXM= # base64 от echo -n "postgres" | base64
  SPRING_R2DBC_PASSWORD: YWRtaW4= # base64 от echo -n "admin" | base64
  JWT_ACCESS_SECRET: eUdXdGdMMmxmT3A4cnpTeVJoTm1TYkMyOTBpUjNpZlVULzMwQVR4UytqWT0= # base64 от echo -n "yGWtgL2lfOp8rzSyRhNmSbC290iR3ifUT/30ATxS+jY=" | base64
  JWT_REFRESH_SECRET: VEs1b3dlM0dZeUdodDR5eC9tR0FzUmk5c2lySTc3MzhIRCtMcmR1RnBEbz0= # base64 от echo -n "TK5owe3GYyGht4yx/mGAsRi9sirI7738HD+LrduFpDo=" | base64

  GOOGLE_AUTH_CLIENT_SECRET: R09DU1BYLUpDb1dCNGFYM0hzS3d0d052cGprUjNvTUdqZG4= # base64 от echo -n "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" | base64
  GOOGLE_AUTH_CLIENT_ID: MTA1OTAyMTgxODc0Ni02Nm00bHQwN2ltajZhZmlwcDd2amRwdnVvNDZkMWpxZC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ== # base64 от echo -n "1059021818746-66m4lt07imj6afipp7vjdpvuo46d1jqd.apps.googleusercontent.com" | base64

  GOOGLE_EMAIL_USERNAME: ZXZnZW5peS5nYXZyaWxvdi5kZXZAZ21haWwuY29t # base64 от echo -n "evgeniy.gavrilov.dev@gmail.com" | base64
  GOOGLE_EMAIL_PASSWORD: YXpkciBkeG5pIGp0bXcgZG90cw== # base64 от echo -n "azdr dxni jtmw dots" | base64

  STRIPE_SECRET_KEY: c2tfdGVzdF81MVMwaEswUnFoekhsOENQSEd4QzZBZHh6N1VsaHd5TDRnaG9vYnNDUlN5Q2lhRW1vbjVaVmJXSEphWTI0RXFBZ2M1aVExOVA1MTE5MVM4RUFuaWNLdU4yMjAwdXRWdThlZUU= # base64 от echo -n "sk_test_51S0hK0RqhzHl8CPHGxC6Adxz7UlhwyL4ghoobsCRSyCiaEmon5ZVbWHJaY24EqAgc5iQ19P51191S8EAnicKuN2200utVu8eeE" | base64
  STRIPE_PUBLIC_KEY: cGtfdGVzdF81MVMwaEswUnFoekhsOENQSFg5S3ZSNFhqQlJaSHJNM3FuSHR2ajJWQzVFdmFzcjN3QU82UzZoT0xkazQ1WjVyY0poMzJNRHdWV3Q4RHJvNDBjeFlRRVF5SjAwQ1pOcGJsVlA= # base64 от echo -n "pk_test_51S0hK0RqhzHl8CPHX9KvR4XjBRZHrM3qnHtvj2VC5Evasr3wAO6S6hOLdk45Z5rcJh32MDwVWt8Dro40cxYQEQyJ00CZNpblVP" | base64
  STRIPE_WEBHOOK_SECRET: d2hzZWNfNWYxNjVmZDQzZWZiY2VhOGI2MzZjZjljZDAyMjAzOTE0OGFiMDRhYjI3MzVhNWNjZThhZDY1MDgyYzUyZWU2Yw== # base64 от echo -n "whsec_5f165fd43efbcea8b636cf9cd022039148ab04ab2735a5cce8ad65082c52ee6c" | base64
# kubectl apply -f secret.yaml